# Generated by Django 5.2.1 on 2025-05-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sub_app_1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
