# Generated by Django 5.2.1 on 2025-05-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AptInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_normal", models.TextField(verbose_name="주소(일반)")),
                ("address_road", models.TextField(verbose_name="주소(도로명)")),
                ("building_no", models.PositiveIntegerField(verbose_name="동 번호")),
                ("floor", models.PositiveIntegerField(verbose_name="층수")),
                ("price", models.PositiveBigIntegerField(verbose_name="가격")),
            ],
        ),
    ]
